-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 17:40:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinicaveterinariadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicaveterinariadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicaveterinariadb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clinicaveterinariadb` ;

-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do cliente.',
  `nome` VARCHAR(100) NOT NULL COMMENT 'Nome do cliente.',
  `telefone` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Telefone de contato do cliente.',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'E-mail do cliente.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`pet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `especie` VARCHAR(50) NULL DEFAULT NULL,
  `raca` VARCHAR(50) NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `pet_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `clinicaveterinariadb`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`veterinario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `especializacao` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `pet_id` INT NULL DEFAULT NULL,
  `veterinario_id` INT NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `formaPagamento` VARCHAR(50) NULL DEFAULT NULL,
  `valorPraticado` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pet_id` (`pet_id` ASC) VISIBLE,
  INDEX `veterinario_id` (`veterinario_id` ASC) VISIBLE,
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `clinicaveterinariadb`.`pet` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `consulta_ibfk_2`
    FOREIGN KEY (`veterinario_id`)
    REFERENCES `clinicaveterinariadb`.`veterinario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`consultaservico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`consultaservico` (
  `consulta_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  INDEX `servico_id` (`servico_id` ASC) VISIBLE,
  CONSTRAINT `consultaservico_ibfk_1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `clinicaveterinariadb`.`consulta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `consultaservico_ibfk_2`
    FOREIGN KEY (`servico_id`)
    REFERENCES `clinicaveterinariadb`.`servico` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `estoque` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clinicaveterinariadb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinariadb`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NULL DEFAULT NULL,
  `produto_id` INT NULL DEFAULT NULL,
  `quantidade` INT NOT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(50) NULL DEFAULT NULL,
  `valor_praticado` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `produto_id` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `venda_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `clinicaveterinariadb`.`cliente` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `venda_ibfk_2`
    FOREIGN KEY (`produto_id`)
    REFERENCES `clinicaveterinariadb`.`produto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
